name: Kaba-Delivery

services:

  alertmanager:
    image: prom/alertmanager:latest
    container_name: API_alertmanager
    restart: unless-stopped
    ports:
      - "9093:9097"
    volumes:
      - ./docker/alertmanager/config.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=:9093'
    networks:
      - backend

  app:
    build: .
    container_name: API_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: API_nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: API_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: backend-app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3307"
    volumes:
      - backend_dbdata:/var/lib/mysql
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: API_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9092:9091"
    depends_on:
      - alertmanager
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: API_grafana
    ports:
      - "3003:3000"
    dns:
    - 8.8.8.8
    - 8.8.4.4
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=richinellelaurence@gmail.com
      - GF_SMTP_PASSWORD=trcscpbtdfptyfhe
      - GF_SMTP_FROM_ADDRESS=richinellelaurence@gmail.com
      - GF_SMTP_FROM_NAME=Grafana SGEE
      - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
    volumes:
      - backend_grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: API_cadvisor
    ports:
      - "8082:8088"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: API_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9202:9201"
    networks:
      - backend

  logstash:
    image: logstash:8.11.0
    container_name: API_logstash
    volumes:
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
      - .:/var/www
    depends_on:
      - elasticsearch
    networks:
      - backend

  kibana:
    image: kibana:8.11.0
    container_name: API_kibana
    ports:
      - "5602:5603"
    depends_on:
      - elasticsearch
    networks:
      - backend

  sonarqube:
    image: sonarqube:community
    container_name: API_sonarqube
    ports:
      - "9002:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
    volumes:
      - backend_sonarqube_data:/opt/sonarqube/data
      - backend_sonarqube_logs:/opt/sonarqube/logs
    networks:
      - backend

  sonar-db:
    image: postgres:15
    container_name: API_sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - backend_sonar_db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  backend_dbdata:
  backend_grafana_data:
  backend_sonarqube_data:
  backend_sonarqube_logs:
  backend_sonar_db:
