sonar.projectKey=richinelle_Kaba_Delivery
sonar.organization=richinelle
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=**/vendor/**,**/storage/**,**/bootstrap/**

